# ------------------------------------------------------------
# Stage 1: Composer dependencies
# ------------------------------------------------------------
FROM composer:2 AS vendor

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install \
    --no-dev \
    --no-interaction \
    --no-progress \
    --no-scripts \
    --prefer-dist \
    --optimize-autoloader


# ------------------------------------------------------------
# Stage 2: Laravel PHP-FPM runtime
# ------------------------------------------------------------
FROM php:8.4-fpm-bookworm AS production

WORKDIR /var/www

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libonig-dev \
        libzip-dev \
    && docker-php-ext-install -j"$(nproc)" \
        pdo_mysql \
        mbstring \
        zip \
        exif \
        pcntl \
        opcache \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY docker/php/php-production.ini \
    /usr/local/etc/php/conf.d/99-production.ini

COPY --chown=www-data:www-data . /var/www

COPY --from=vendor \
    --chown=www-data:www-data \
    /app/vendor \
    /var/www/vendor


RUN mkdir -p \
        storage/framework/cache \
        storage/framework/sessions \
        storage/framework/views \
        storage/logs \
        bootstrap/cache \
    && chown -R www-data:www-data \
        storage \
        bootstrap/cache

RUN php artisan package:discover --ansi

USER www-data

EXPOSE 9000

CMD ["php-fpm", "-F"]