apiVersion: v1
kind: Service
metadata:
  name: crm-app
  namespace: crm-preprod
  labels:
    app.kubernetes.io/name: crm-app
    app.kubernetes.io/part-of: laravel-crm
    environment: preprod
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: crm-app
  ports:
    - name: fastcgi
      protocol: TCP
      port: 9000
      targetPort: fastcgi
